/* BILS Experience Update 14 - geometry of approved v12 + bilingual descriptions */
(() => {
  const data = [
    {date:'09/2017 - Oggi',company:'Abitare Co.',role:'Senior Graphic & Digital Designer',items:[['Identita visiva per iniziative immobiliari, brochure, capitolati e presentazioni commerciali.','Visual identity for real estate developments, brochures, specifications and sales presentations.'],['Video emozionali, teaser, siti web e landing page per i lanci commerciali.','Emotional videos, teasers, websites and landing pages for commercial launches.'],['Post-produzione di fotografie, immagini e render 3D per digitale e stampa.','Post-production of photography, images and 3D renders for digital and print.'],['Tool digitali interni per automatizzare attivita e migliorare i flussi del marketing.','Internal digital tools to automate tasks and improve marketing workflows.'],['Comunicazione visiva di showroom e uffici vendita: dresswall, pannelli e vetrofanie.','Visual communication for showrooms and sales offices: dress walls, panels and window graphics.']]},
    {date:'06/2017 - 08/2017',company:'Gruppo Mondadori',role:'Graphic Designer Editoriale',items:[['Post-produzione fotografica e correzione colore.','Photography post-production and color correction.'],['Controllo tecnico-editoriale dei contenuti.','Technical and editorial content review.'],['Preparazione definitiva dei materiali prima dell invio allo stampatore.','Final preparation of materials before delivery to the printer.']]},
    {date:'04/2014 - 06/2017',company:'Casa.it',role:'Creative Designer',items:[['Campagne display e banner statici, dinamici e HTML5.','Display campaigns and static, dynamic and HTML5 banners.'],['DEM e contenuti promozionali personalizzati.','Email marketing and customized promotional content.'],['Produzione e pubblicazione con Adobe Creative Cloud, Google Web Designer e DoubleClick for Publishers.','Production and publishing with Adobe Creative Cloud, Google Web Designer and DoubleClick for Publishers.']]},
    {date:'09/2012 - 03/2014',company:'Link S.p.A.',role:'Consulente Grafico',items:[['Impaginazione e aggiornamento del catalogo aziendale.','Layout and updating of the company catalog.'],['Post-produzione delle immagini di prodotto.','Post-production of product imagery.'],['Creazione di materiali grafici promozionali.','Creation of promotional graphic materials.']]},
    {date:'06/2012 - 09/2012',company:'RCS MediaGroup',role:'Operatore Grafico',items:[['Impaginazione editoriale.','Editorial layout and page design.'],['Ritocco fotografico.','Professional photo retouching.'],['Adattamento di copertine per le testate del gruppo.','Cover adaptations for the group publications.']]}
  ];
  const story=document.querySelector('.experience-story'); if(!story)return;
  story.innerHTML=`<div class="experience-sticky exp14-stage"><div class="exp14-left"><h2><span>Un percorso costruito</span><br>tra creativita, editoria e digitale.</h2><p>A journey shaped by creativity, publishing and digital innovation.</p><div class="exp14-date">${data[0].date}</div><div class="exp14-progress"><i></i></div></div><div class="exp14-scene"><div class="exp14-ring"></div><div class="exp14-nodes">${data.map((e,i)=>`<div class="exp14-node" data-index="${i}"><div><strong>${e.company}</strong><span>${e.role}</span></div></div>`).join('')}</div><div class="exp14-copy"><ul></ul></div></div></div>`;
  const nodes=[...story.querySelectorAll('.exp14-node')],date=story.querySelector('.exp14-date'),list=story.querySelector('.exp14-copy ul'),bar=story.querySelector('.exp14-progress i'); let active=-1;
  function scramble(target){const chars='0123456789/-';let f=0;clearInterval(scramble.t);scramble.t=setInterval(()=>{date.textContent=target.split('').map((c,i)=>c===' '?' ':(f>7+i?c:chars[Math.floor(Math.random()*chars.length)])).join('');if(++f>21){clearInterval(scramble.t);date.textContent=target}},28)}
  function content(i){if(i===active)return;active=i;scramble(data[i].date);list.classList.remove('swap');list.innerHTML=data[i].items.map(x=>`<li><span>${x[0]}</span><em>${x[1]}</em></li>`).join('');requestAnimationFrame(()=>list.classList.add('swap'))}
  function render(){const r=story.getBoundingClientRect(),travel=Math.max(1,story.offsetHeight-innerHeight),p=Math.max(0,Math.min(1,-r.top/travel)),stage=p*(data.length-1),nearest=Math.min(data.length-1,Math.floor(stage+.5));content(nearest);bar.style.width=`${p*100}%`;const mobile=matchMedia('(max-width:760px)').matches,rx=mobile?255:510,ry=mobile?225:465;nodes.forEach((n,i)=>{const rel=i-stage,a=(Math.PI-rel*55*Math.PI/180),x=Math.cos(a)*rx,y=Math.sin(a)*ry,abs=Math.abs(rel),scale=Math.max(.16,1.68-Math.min(1,abs)*1.5),copy=Math.max(0,Math.min(1,1.15-abs*2.8));n.style.setProperty('--x',`${x}px`);n.style.setProperty('--y',`${y}px`);n.style.setProperty('--s',scale);n.style.setProperty('--copy',copy);n.style.opacity=abs>1.08?0:Math.max(.82,1-abs*.12);n.classList.toggle('active',i===nearest)})}
  const css=document.createElement('style');css.textContent=`
  .experience-story{height:520vh!important}.exp14-stage{position:sticky!important;top:90px!important;height:calc(100vh - 108px)!important;min-height:680px!important;display:grid!important;grid-template-columns:35% 65%!important;align-items:center!important;padding:52px!important;overflow:hidden!important;background:#080f1c!important}.exp14-left{position:relative;z-index:50}.exp14-left h2{margin:0;font-size:clamp(2rem,3.4vw,3.55rem);line-height:1.03;letter-spacing:-.05em}.exp14-left h2 span,.exp14-date{color:var(--yellow)}.exp14-left>p{color:var(--muted);font-style:italic}.exp14-date{font-size:clamp(1.45rem,2.55vw,2.5rem);font-weight:700;font-variant-numeric:tabular-nums}.exp14-progress{height:2px;margin-top:18px;background:rgba(255,255,255,.1)}.exp14-progress i{display:block;height:100%;background:var(--yellow)}.exp14-scene{position:relative;height:100%;min-height:620px;overflow:visible}.exp14-ring{position:absolute;left:96%;top:50%;width:1020px;height:1020px;transform:translate(-50%,-50%);border:2px solid rgba(252,255,131,.34);border-radius:50%}.exp14-nodes{position:absolute;left:96%;top:50%}.exp14-node{--x:-510px;--y:0;--s:.16;--copy:0;position:absolute;width:158px;height:158px;transform:translate(calc(-50% + var(--x)),calc(-50% + var(--y))) scale(var(--s));display:grid;place-items:center;padding:16px;border-radius:50%;background:var(--yellow);color:#08101d;text-align:center;will-change:transform,opacity;box-shadow:0 18px 54px rgba(0,0,0,.28)}.exp14-node>div{opacity:var(--copy)}.exp14-node strong,.exp14-node span{display:block}.exp14-node strong{font-size:1.05rem}.exp14-node span{margin-top:7px;font-size:.66rem}.exp14-node.active{box-shadow:0 28px 85px rgba(252,255,131,.22)}.exp14-copy{position:absolute;z-index:30;left:58%;top:50%;width:39%;transform:translateY(-50%)}.exp14-copy ul{list-style:none;margin:0;padding:0}.exp14-copy li{position:relative;margin-bottom:18px;padding-left:32px}.exp14-copy li:before{content:'✓';position:absolute;left:0;color:var(--yellow);font-weight:800}.exp14-copy span{display:block;color:var(--text);font-size:1rem;line-height:1.42}.exp14-copy em{display:block;margin-top:5px;color:var(--muted);font-size:.74rem;line-height:1.4;font-style:italic}.exp14-copy ul.swap{animation:swap14 .34s ease}@keyframes swap14{from{opacity:0;transform:translateY(15px)}to{opacity:1;transform:none}}
  @media(max-width:1100px){.exp14-stage{padding:34px;grid-template-columns:38% 62%}.exp14-ring,.exp14-nodes{left:102%}.exp14-ring{width:820px;height:820px}.exp14-copy{left:59%;width:38%}.exp14-copy span{font-size:.82rem}.exp14-copy em{font-size:.67rem}}
  @media(max-width:760px){.experience-story{height:480vh!important}.exp14-stage{top:72px!important;height:calc(100vh - 84px)!important;min-height:720px!important;grid-template-columns:1fr!important;align-content:start!important;padding:22px!important}.exp14-left h2{font-size:1.85rem}.exp14-date{font-size:1.25rem}.exp14-scene{height:440px;min-height:440px;overflow:hidden}.exp14-ring,.exp14-nodes{left:106%;top:52%}.exp14-ring{width:510px;height:510px}.exp14-node{width:110px;height:110px}.exp14-copy{left:58%;top:52%;width:40%}.exp14-copy li{margin-bottom:8px;padding-left:22px}.exp14-copy span{font-size:.74rem}.exp14-copy em{font-size:.61rem;margin-top:3px}}
  `;document.head.appendChild(css);addEventListener('scroll',render,{passive:true});addEventListener('resize',render);render();
})();
