/* Experience Orbit Update 09. Loaded after app.js. */
(() => {
 const data=[
 {date:'09/2017 - Oggi',company:'Abitare Co.',role:'Senior Graphic & Digital Designer',items:['Identità visiva per iniziative immobiliari, brochure, capitolati e presentazioni commerciali.','Video emozionali, teaser, siti web e landing page per i lanci commerciali.','Post-produzione di fotografie, immagini e render 3D per digitale e stampa.','Tool digitali interni per automatizzare attività e migliorare i flussi del marketing.','Comunicazione visiva di showroom e uffici vendita: dresswall, pannelli e vetrofanie.']},
 {date:'06/2017 - 08/2017',company:'Gruppo Mondadori',role:'Graphic Designer Editoriale',items:['Post-produzione fotografica e correzione colore.','Controllo tecnico-editoriale dei contenuti.','Preparazione definitiva dei materiali prima dell’invio allo stampatore.']},
 {date:'04/2014 - 06/2017',company:'Casa.it',role:'Creative Designer',items:['Campagne display e banner statici, dinamici e HTML5.','DEM e contenuti promozionali personalizzati.','Produzione e pubblicazione con Adobe Creative Cloud, Google Web Designer e DoubleClick for Publishers.']},
 {date:'09/2012 - 03/2014',company:'Link S.p.A.',role:'Consulente Grafico',items:['Impaginazione e aggiornamento del catalogo aziendale.','Post-produzione delle immagini di prodotto.','Creazione di materiali grafici promozionali.']},
 {date:'06/2012 - 09/2012',company:'RCS MediaGroup',role:'Operatore Grafico',items:['Impaginazione editoriale.','Ritocco fotografico.','Adattamento di copertine per le testate del gruppo.']}];
 const story=document.querySelector('.experience-story'); if(!story)return;
 story.innerHTML=`<div class="experience-sticky experience-orbit-stage"><div class="exp-left"><h2><span>Un percorso costruito</span><br>tra creatività, editoria e digitale.</h2><p>A journey shaped by creativity, publishing and digital innovation.</p><div class="exp-date">${data[0].date}</div><div class="exp-progress"><i></i></div></div><div class="exp-wheel"><div class="exp-ring"></div><div class="exp-nodes">${data.map((e,i)=>`<div class="career-node" data-index="${i}"><strong>${e.company}</strong><span>${e.role}</span></div>`).join('')}</div></div><div class="exp-right"><ul></ul></div></div>`;
 const nodes=[...story.querySelectorAll('.career-node')],date=story.querySelector('.exp-date'),list=story.querySelector('.exp-right ul'),bar=story.querySelector('.exp-progress i');let active=-1;
 function scramble(target){const chars='0123456789/-';let f=0;clearInterval(scramble.t);scramble.t=setInterval(()=>{date.textContent=target.split('').map((c,i)=>c===' '?' ':(f>7+i?c:chars[Math.floor(Math.random()*chars.length)])).join('');if(++f>21){clearInterval(scramble.t);date.textContent=target}},28)}
 function content(i){if(i===active)return;active=i;scramble(data[i].date);list.innerHTML=data[i].items.map(x=>`<li>${x}</li>`).join('');list.classList.remove('swap');requestAnimationFrame(()=>list.classList.add('swap'))}
 function draw(){const r=story.getBoundingClientRect(),travel=Math.max(1,story.offsetHeight-innerHeight),p=Math.max(0,Math.min(1,-r.top/travel)),float=p*(data.length-1),index=Math.min(data.length-1,Math.floor(float+.5));content(index);bar.style.width=`${p*100}%`;nodes.forEach((n,i)=>{const rel=i-float,a=rel*52*Math.PI/180,x=Math.sin(a)*450,y=-Math.cos(a)*330,d=Math.min(1,Math.abs(rel)),s=1.58-d*.92;n.style.setProperty('--x',`${x}px`);n.style.setProperty('--y',`${y}px`);n.style.setProperty('--scale',s.toFixed(3));n.style.opacity=Math.max(.18,1-Math.max(0,Math.abs(rel)-1.2)*.55);n.classList.toggle('is-active',i===index)})}
 const s=document.createElement('style');s.textContent=`.experience-story{height:520vh!important}.experience-orbit-stage{position:sticky!important;top:90px!important;height:calc(100vh - 108px)!important;min-height:680px!important;display:grid!important;grid-template-columns:.88fr 1.12fr 1fr!important;align-items:center!important;gap:34px!important;padding:52px!important;overflow:hidden!important;background:#080f1c!important}.exp-wheel{position:relative!important;height:100%!important;min-height:620px!important}.exp-ring{position:absolute!important;left:50%!important;top:50%!important;width:880px!important;height:880px!important;transform:translate(-50%,-50%)!important;border:2px solid rgba(252,255,131,.34)!important;border-radius:50%!important}.exp-nodes{position:absolute!important;left:50%!important;top:50%!important}.career-node{--x:0px;--y:0px;--scale:.66;position:absolute!important;width:156px!important;height:156px!important;transform:translate(calc(-50% + var(--x)),calc(-50% + var(--y))) scale(var(--scale))!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;padding:16px!important;border-radius:50%!important;background:var(--yellow)!important;color:#08101d!important;text-align:center!important;will-change:transform,opacity!important}.career-node strong{font-size:1.05rem!important}.career-node span{margin-top:7px!important;font-size:.66rem!important}.exp-left h2{font-size:clamp(2rem,3.4vw,3.55rem)!important;line-height:1.03!important;letter-spacing:-.05em!important}.exp-left h2 span,.exp-date{color:var(--yellow)!important}.exp-left>p{color:var(--muted)!important;font-style:italic!important}.exp-date{font-size:clamp(1.45rem,2.55vw,2.5rem)!important;font-weight:700!important}.exp-progress{height:2px!important;background:rgba(255,255,255,.1)!important}.exp-progress i{display:block!important;height:100%!important;background:var(--yellow)!important}.exp-right ul{list-style:none!important;padding:0!important}.exp-right li{position:relative!important;margin-bottom:18px!important;padding-left:32px!important}.exp-right li:before{content:'✓';position:absolute;left:0;color:var(--yellow);font-weight:800}.exp-right ul.swap{animation:swap .34s ease}@keyframes swap{from{opacity:0;transform:translateY(15px)}to{opacity:1;transform:none}}@media(max-width:760px){.experience-story{height:480vh!important}.experience-orbit-stage{top:72px!important;height:calc(100vh - 84px)!important;min-height:700px!important;grid-template-columns:1fr!important;padding:22px!important}.exp-wheel{height:260px!important;min-height:260px!important;overflow:hidden!important}.exp-ring{width:430px!important;height:430px!important}.career-node{width:110px!important;height:110px!important}.exp-right li{margin-bottom:6px!important;font-size:.72rem!important}}`;document.head.appendChild(s);addEventListener('scroll',draw,{passive:true});addEventListener('resize',draw);draw();
})();
